name: Checkstyle

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Run Checkstyle
      run: |
       if git rev-parse HEAD^ >/dev/null 2>&1; then
         REVISION=HEAD^
         else
         REVISION=HEAD~1
       fi
    
       # Get modified files between the current commit and the parent commit
       MODIFIED_FILES=$(git diff --name-only $REVISION HEAD)
    
       # Run Checkstyle on modified Java files
       for FILE in $MODIFIED_FILES; do
         if [[ "$FILE" == *.java ]]; then
           checkstyle -c checkstyle.xml -f xml -o checkstyle_report.xml "$FILE"
         fi
       done

    - name: List files
      run: |
        ls
        cat checkstyle_report.xml   