name: Checkstyle

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    # - name: Install Checkstyle
    #   run: sudo apt-get install checkstyle    
    
    - id: file_changes
      uses: trilom/file-changes-action@v1.2.3
      with:
        output: ' '
        fileOutput: ' '
    - name: test
      run: |
        cat $HOME/files.txt      

    #- name: Run Checkstyle
    #  run: |

       #latest_commit=$(git rev-parse HEAD)
       #parent_commit=$(git rev-parse HEAD^)
       #modified_files=$(git diff --name-only $parent_commit $latest_commit)
       # for file in $modified_files; do
       #   if [[ "$file" == *.java ]]; then
       #     checkstyle -c checkstyle.xml -f xml -o checkstyle_report.xml "$file"
       #   fi
       # done

       #git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.java$' | xargs checkstyle -c config/checkstyle/checkstyle.xml -f xml -o checkstyle_report.xml
      #working-directory: ${{ github.workspace }}

    # - name: List files
    #   run: |
    #     ls
    #     cat checkstyle_report.xml   