name: Checkstyle

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Run Checkstyle
      run: |
       # Get the latest commit hash
       #latest_commit=$(git rev-parse HEAD)

       # Get the parent commit hash
       #parent_commit=$(git rev-parse HEAD^)

       # Get the modified files between the latest commit and the parent commit
       #modified_files=$(git diff --name-only $parent_commit $latest_commit)

       # Loop through the modified files
        #for file in $modified_files; do
          # Check if the file is a Java file
         # if [[ "$file" == *.java ]]; then
            # Run Checkstyle on the modified Java file
          #  checkstyle -c checkstyle.xml -f xml -o checkstyle_report.xml "$file"
          #fi
        #done

        # Fetch latest changes from remote repository
         git fetch origin

          # Get the latest commit hash
         latest_commit=$(git log --format="%H" -n 1)

          # Get the parent commit hash
         parent_commit=$(git log --format="%H" -n 1 HEAD^)

          # Get the modified files between the latest commit and the parent commit
         modified_files=$(git diff --name-only $parent_commit $latest_commit)

          # Print the modified files
         echo "Modified files in the latest commit:"
         echo "$modified_files"

    - name: List files
      run: |
        ls
        cat checkstyle_report.xml   