name: CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Build project with Maven
        run: mvn -B package --file pom.xml

      - name: Create staging directory and copy JAR files
          run: |
            mkdir staging
            cp target/*.jar staging

      - name: Upload artifact
          uses: actions/upload-artifact@v1
              with:
                name: Package
                path: staging

      #- name: Upload Artifacts
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: my-artifact
      #    path: ./target
      #- name: Download Artifact
      #  uses: actions/download-artifact@v2
      #  with:
      #    name: /home/runner/work/POC/POC/target/jb-hello-world-maven-0.2.0-shaded.jar
      #    path: ./downloaded-artifact