name: publish-job

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  publish-job:
    runs-on: ubuntu-latest
    needs: [cicd]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build and package
        run: mvn -B package --file pom.xml -DskipTests

      - name: Create staging directory and copy JAR files
        run: |
          mkdir staging
          cp target/*.jar staging

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging
