publish-job:
  runs-on: ubuntu-latest
  needs: [cicd]
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: mvn -B package --file pom.xml -DskipTests
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging